### ISSUE TITLE
Config Check - Oldest Backups

### ISSUE THREAD

**Issue by dtaylor293** [marcingminski/sqlwatch#212] opened 2020-09-17 16:31 UTC
**Describe the bug**
A very minor thing I noticed, apologies if this has been picked up elsewhere. I did check but couldn't see anything.

The code for the following checks on sqlwatch_config_check appears to return an incorrect value:
check_id -17 Oldest LOG backup (minutes)
check_id -18 Oldest DATA backup (days)

The description for both checks suggests this check is to identify databases that have no recent log or backup (either full or diff). The msdb.dbo.backupset table in my environment retains 30 days history, so when running the code for the check it shows the max value, which is effectively the oldest entry in for each backup type in the msdb.dbo.backupset table. 

**To Reproduce**
--For check_id -17 run the following SQL code;
--Oldest log
DECLARE @output int;
select @output=isnull(max(datediff(minute,backup_finish_date,getdate())),999) from sys.databases d  left join msdb.dbo.backupset bs on bs.database_name = d.name   and bs.type = 'L' where d.recovery_model_desc <> 'SIMPLE' and d.name not in ('tempdb')
select @output
GO

--For check_id -18 run the following SQL code;
--Oldest backup
DECLARE @output int;
select @output=isnull(max(datediff(day,backup_finish_date,getdate())),0)  from sys.databases d  left join msdb.dbo.backupset bs   on bs.database_name = d.name   and bs.type <> 'L'  where d.name not in ('tempdb')
select @output
GO
 
**Expected behavior**
Logs are backed up every 20 minutes and are completing successfully, so after setting the required config values for my environment, I would expect the check to warn if logs had not been backed up for more than 20 minutes and critical after 60 minutes. 

I have replaced the code in the field check_query on [dbo].[sqlwatch_config_check] with the following which I have been running with for a few days and so far has been working;
--For check_id -17
SELECT @output=isnull(max(datediff(minute,backup_finish_date,getdate())),999)
FROM (
SELECT bs.database_name, 
    MAX(CASE WHEN bs.type = 'L' THEN bs.backup_finish_date ELSE NULL END) AS backup_finish_date
from sys.databases d  
	left join msdb.dbo.backupset bs   on bs.database_name = d.name   and bs.type = 'L'  where d.recovery_model_desc <> 'SIMPLE'  and d.name not in ('tempdb')
GROUP BY bs.database_name
) backupset

--For check_id -18
SELECT @output=isnull(max(datediff(day,backup_finish_date,getdate())),0)
FROM (
SELECT bs.database_name, 
    MAX(CASE WHEN bs.type <> 'L' THEN bs.backup_finish_date ELSE NULL END) AS backup_finish_date
from sys.databases d  
	left join msdb.dbo.backupset bs   on bs.database_name = d.name   and bs.type <> 'L'  where d.name not in ('tempdb')
GROUP BY bs.database_name
) backupset

/*
--Update code if needed
--Set new config check for Check_id = -17
UPDATE [dbo].[sqlwatch_config_check]
SET check_query = 'SELECT @output=isnull(max(datediff(minute,backup_finish_date,getdate())),999)
FROM (
SELECT bs.database_name, 
    MAX(CASE WHEN bs.type = ''L'' THEN bs.backup_finish_date ELSE NULL END) AS backup_finish_date
from sys.databases d  
	left join msdb.dbo.backupset bs on bs.database_name = d.name and bs.type = ''L''  where d.recovery_model_desc <> ''SIMPLE''  and d.name not in (''tempdb'')
GROUP BY bs.database_name
) backupset'
WHERE Check_id = -17
GO

--Set new config check for Check_id = -18
UPDATE [dbo].[sqlwatch_config_check]
SET check_query = 'SELECT @output=isnull(max(datediff(day,backup_finish_date,getdate())),0)
FROM (
SELECT bs.database_name, 
    MAX(CASE WHEN bs.type <> ''L'' THEN bs.backup_finish_date ELSE NULL END) AS backup_finish_date
from sys.databases d  
	left join msdb.dbo.backupset bs on bs.database_name = d.name and bs.type <> ''L''  where d.name not in (''tempdb'')
GROUP BY bs.database_name
) backupset'
WHERE Check_id = -18
GO
*/

The IO stats identical to the original query, so hopefully no impact from a performance perspective.

**Windows Server (please complete the following information):**
 - OS Version: Windows Server 2012 R2

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2016 SP2
 - SQL Edition: Standard
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here: 
SQL Server Management Studio					15.0.18333.0
SQL Server Management Objects (SMO)			16.100.37971.0
Microsoft Analysis Services Client Tools				15.0.19153.0
Microsoft Data Access Components (MDAC)			10.0.18362.1
Microsoft MSXML								3.0 6.0
Microsoft .NET Framework						4.0.30319.42000
Operating System							        10.0.18363
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.5.7507.41097

**Comment by marcingminski** [comment] 2020-09-18 18:57
Looks like a duplicate of https://github.com/marcingminski/sqlwatch/issues/191

**Closed as completed** 2020-09-18 18:57 UTC

**Comment by dtaylor293** [comment] 2020-09-19 18:51
Hi Marc,

Thanks for the response. SQLWATCH is fantastic 👍  

I did reference the problem raised in Issue #191 and amended the column name from last_backup_finish_date to backupfinish_date in my query, but this is a different problem. The results returned by the original query give the oldest entry in for each backup type in the msdb.dbo.backupset table, my understanding (which may be wrong!) was that the check should show a backup over x amount of time.

Thanks

**Comment by simonwhybrow-cbre** [comment] 2020-09-20 08:58
Hi @dtaylor293 

Think this is the same as https://github.com/marcingminski/sqlwatch/issues/179 which is referenced in https://github.com/marcingminski/sqlwatch/issues/191.

Think @marcingminski has got it covered in the next major release.

Thanks
Simon

**Comment by dtaylor293** [comment] 2020-09-20 10:27
Brilliant. Thank you @simonwhybrow-cbre
