### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by nmo0ory** [marcingminski/sqlwatch#214] opened 2020-10-25 07:30 UTC

**Comment by nmo0ory** [comment] 2020-10-25 07:31
hello,
i have an offline server that i want to install on it dbwatch 
i try to use Deploy Data-tire application but i keep gitting this error 
how can i fix it 

TITLE: Microsoft SQL Server Management Studio
------------------------------

Could not deploy package.
Warning SQL72038: The object [SQLWATCH_blockers] already exists in database with a different definition and will not be altered.
Warning SQL72038: The object [SQLWATCH_long_queries] already exists in database with a different definition and will not be altered.
Warning SQL72038: The object [SQLWATCH_waits] already exists in database with a different definition and will not be altered.
Error SQL72014: .Net SqlClient Data Provider: Msg 50000, Level 16, State 1, Procedure dbo.usp_sqlwatch_internal_run_job, Line 61 Job 'SQLWATCH-INTERNAL-CHECKS' has not finished successfuly or the state is not known.
Error SQL72045: Script execution error.  The executed script:
BEGIN TRANSACTION;

MERGE INTO dbo.sqlwatch_config_sql_instance
 AS target
USING (SELECT @@SERVERNAME AS [servername],
              0 AS [repo_collector_is_active]) AS source ON target.sql_instance = source.[servername]
WHEN NOT MATCHED THEN INSERT (sql_instance, [repo_collector_is_active]) VALUES (source.[servername], source.[repo_collector_is_active]);

MERGE INTO [dbo].[sqlwatch_meta_server]
 AS target
USING (SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')) AS [physical_name],
              CONVERT (sysname, @@SERVERNAME) AS [servername],
              CONVERT (sysname, @@SERVICENAME) AS [service_name],
              CONVERT (VARCHAR (50), local_net_address) AS [local_net_address],
              CONVERT (VARCHAR (50), local_tcp_port) AS [local_tcp_port],
              DATEDIFF(mi, GETUTCDATE(), GETDATE()) AS [utc_offset_minutes],
              @@VERSION AS [sql_version]
       FROM   sys.dm_exec_connections
       WHERE  session_id = @@spid) AS source ON target.[se
 (Microsoft.SqlServer.Dac)

------------------------------
BUTTONS:

OK
------------------------------

**Comment by marcingminski** [comment] 2020-10-25 19:09
I believe this is a duplicate of https://github.com/marcingminski/sqlwatch/issues/198 
Can you confirm?

**Closed as completed** 2021-02-03 17:25 UTC
