### ISSUE TITLE
Job SQLWATCH-INTERNAL-CHECKS failing 

### ISSUE THREAD

**Issue by MartinBarhon** [marcingminski/sqlwatch#185] opened 2020-07-07 17:39 UTC
SQLWATCH-INTERNAL-CHECKS is failing at random
![image](https://user-images.githubusercontent.com/67230207/86816575-4390ca80-c084-11ea-9dd5-35a462fe011a.png)
When I log this to text file there is only

Job 'SQLWATCH-INTERNAL-CHECKS' : Step 1, 'dbo.usp_sqlwatch_internal_process_checks' : Began Executing 2020-07-07 18:16:43

Processing actions for check. [SQLSTATE 01000]
FAILED_QUERY      

When I look to [dbo].[sqlwatch_app_log] there are for this time error lines, see attached file. 

[sqlwatch_app_log.zip](https://github.com/marcingminski/sqlwatch/files/4886289/sqlwatch_app_log.zip)

It is the same on several SQL Server instances.

I use actual version of SQLWATCH 2.5.7460.35921 on SQL Server 2017 CU20.

**Comment by MartinBarhon** [comment] 2020-07-08 17:00
There are two log files. First when it fails and second which succeeded one minute later.

[SQLWATCH-INTERNAl-CHECKS_0xE023A9952C78244FB5388BC65E9FD1C9_1_20200708_184843.txt](https://github.com/marcingminski/sqlwatch/files/4892119/SQLWATCH-INTERNAl-CHECKS_0xE023A9952C78244FB5388BC65E9FD1C9_1_20200708_184843.txt)
[SQLWATCH-INTERNAl-CHECKS_0xE023A9952C78244FB5388BC65E9FD1C9_1_20200708_184943.txt](https://github.com/marcingminski/sqlwatch/files/4892120/SQLWATCH-INTERNAl-CHECKS_0xE023A9952C78244FB5388BC65E9FD1C9_1_20200708_184943.txt)

**Comment by cheche-usc** [comment] 2020-08-27 10:40
I also have errors but in my case the error is because of an invalid column name "last_backup_finish_date" in this query:

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON 
SET ANSI_WARNINGS OFF
select @output=isnull(max(datediff(minute,last_backup_finish_date,getdate())),999)
from sys.databases d
left join msdb.dbo.backupset bs
	on bs.database_name = d.name
	and bs.type = 'L'
where d.recovery_model_desc <> 'SIMPLE'
and d.name not in ('tempdb')

**Comment by marcingminski** [comment] 2020-08-29 21:21
@cheche-usc yours's is a duplicate of https://github.com/marcingminski/sqlwatch/issues/191

**Comment by cheche-usc** [comment] 2020-11-11 12:42
> @cheche-usc yours's is a duplicate of #191

I have executed the script "SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Post-Deployment/Reference-Data/Script.PostDeployment-CreateDefaultChecks.sql" of "Fixed #191" but the problem persists. What am I doing wrong?

**Comment by marcingminski** [comment] 2020-11-12 10:42
I believe the fix will be released in version 3.0

**Comment by marcingminski** [comment] 2021-05-02 17:03
Has this been fixed?

**Comment by cheche-usc** [comment] 2021-05-21 11:18
I have installed Release 4.1. This issue has been fixed. Thank you very much!

**Closed as completed** 2021-05-21 11:19 UTC
