### ISSUE TITLE
Install-DbaSqlWatch Error with miss sqlos.wait_completed

### ISSUE THREAD

**Issue by jortygu** [marcingminski/sqlwatch#262] opened 2021-04-16 07:37 UTC
**Did you check DOCS to make sure there is no workaround?**  yes

**Describe the bug**
when install DbaSqlWatch,it throw miss sqlos.wait_completed error as below.

**To Reproduce**
1. Install-DbaSqlWatch -SqlInstance 192.168.3.121 -Database SQLWATCH -PreRelease

**Expected behavior**
install DbaSqlWatch success

**Screenshots**
![image](https://user-images.githubusercontent.com/43945927/114988201-a42d1d80-9ec8-11eb-92df-884a124352a8.png)

**Windows Server (please complete the following information):**
 - OS Version: Windows 2012 R2

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2012 SP1
 - SQL Edition: Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.0.0.0
 
**Additional context**

**Comment by marcingminski** [comment] 2021-04-16 09:57
Yes, duplicate of https://github.com/marcingminski/sqlwatch/issues/259

**Closed as completed by marcingminski** 2021-04-16 09:57 UTC

**Comment by marcingminski** [comment] 2021-04-16 13:31
See if this works for you:
https://github.com/marcingminski/sqlwatch/issues/259#issuecomment-821178737
